// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/fyk7/code-snippets-app/app/config"
	"github.com/fyk7/code-snippets-app/app/infrastructure/database"
	"github.com/fyk7/code-snippets-app/app/interface_adapter/repository"
	"github.com/fyk7/code-snippets-app/app/usecase"
	"time"
)

// Injectors from wire.go:

func Initialize(cfg *config.Config, timeout time.Duration) *ServiceContainer {
	db := database.NewDB(cfg)
	snippetRepository := interface_adapter.NewSnippetRepository(db)
	snippetService := usecase.NewSnippetService(snippetRepository, timeout)
	tagRepository := interface_adapter.NewTagRepository(db)
	tagService := usecase.NewTagService(tagRepository, timeout)
	userRepository := interface_adapter.NewUserRepository(db)
	userService := usecase.NewUserService(userRepository, timeout)
	serviceContainer := NewServiceContainer(snippetService, tagService, userService)
	return serviceContainer
}
